name: Tagged Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create-tagged-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          
      - name: Get tag
        id: get_tag
        run: echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 20.x

      - name: Debug Node.js Version
        run: node -v

      - name: Debug NPM Version
        run: npm -v

      - name: Navigate to web directory
        run: cd ./web

      - name: Install dependencies
        run: cd ./web && npm install
        
      - name: Debug Installed Packages
        run: cd ./web && npm list
        
      - name: Build project
        run: cd ./web && npm run build

      - name: Debug Build Output
        run: ls -la ./web

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ env.VERSION_TAG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
